apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-cd-toolkit-config
  labels:
    app.kubernetes.io/name: ci-cd-toolkit
data:
  APP_ENV: "production"
  APP_VERSION: "0.1.0"
  PORT: "8000"
  LOG_LEVEL: "info"
  REDIS_URL: "redis://redis-svc:6379/0"
